#!/usr/bin/env bash
# Pull all secrets from a Bitwarden Secrets Manager project into .env.local.
#
# Requires the `bws` CLI installed:   brew install bitwarden/tap/bws
# Requires `jq` installed:            brew install jq
#
# Required env (export in your shell rc or pass inline):
#   BWS_ACCESS_TOKEN — machine-account token from Bitwarden Secrets Manager
#   BWS_PROJECT_ID   — project ID that holds the side-letter extractor secrets
#
# Usage:
#   ./scripts/env-pull.sh
#
# Overwrites .env.local. Bitwarden is the source of truth.

set -euo pipefail

: "${BWS_ACCESS_TOKEN:?Set BWS_ACCESS_TOKEN (Bitwarden Secrets Manager access token)}"
: "${BWS_PROJECT_ID:?Set BWS_PROJECT_ID}"

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
out="${repo_root}/.env.local"

if ! command -v bws >/dev/null 2>&1; then
  echo "bws CLI not found. Install with: brew install bitwarden/tap/bws" >&2
  exit 1
fi
if ! command -v jq >/dev/null 2>&1; then
  echo "jq not found. Install with: brew install jq" >&2
  exit 1
fi

json="$(bws secret list "${BWS_PROJECT_ID}" --output json)"

{
  echo "# Generated by scripts/env-pull.sh from Bitwarden Secrets Manager"
  echo "# Do NOT edit by hand; re-run the script after rotating a secret."
  echo "${json}" | jq -r '.[] | "\(.key)=\(.value | @sh)"'
} > "${out}"

count=$(($(wc -l < "${out}") - 2))
echo "Wrote ${out} with ${count} secret(s)."
